// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt77tClWO581K8oItunWrlh7TMTYiBu5A',
    appId: '1:565285676661:web:1b6b80bb0edd0d221ffa3c',
    messagingSenderId: '565285676661',
    projectId: 'notemind-app-7e7b4',
    authDomain: 'notemind-app-7e7b4.firebaseapp.com',
    storageBucket: 'notemind-app-7e7b4.firebasestorage.app',
    measurementId: 'G-G5EBYC9T6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxpFl6cqQ2zBNXjZ1e9hO7L_kAK52FxT0',
    appId: '1:565285676661:android:a2abf0cf6b630f0a1ffa3c',
    messagingSenderId: '565285676661',
    projectId: 'notemind-app-7e7b4',
    storageBucket: 'notemind-app-7e7b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHiwYj7j7bpKUYnrlcZ1vORtCSNAUTPqo',
    appId: '1:565285676661:ios:32427f699b36c6ea1ffa3c',
    messagingSenderId: '565285676661',
    projectId: 'notemind-app-7e7b4',
    storageBucket: 'notemind-app-7e7b4.firebasestorage.app',
    iosClientId: '565285676661-q7fquei91l1ciq7jk80h9k5pl0kam18j.apps.googleusercontent.com',
    iosBundleId: 'com.example.notemindApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHiwYj7j7bpKUYnrlcZ1vORtCSNAUTPqo',
    appId: '1:565285676661:ios:32427f699b36c6ea1ffa3c',
    messagingSenderId: '565285676661',
    projectId: 'notemind-app-7e7b4',
    storageBucket: 'notemind-app-7e7b4.firebasestorage.app',
    iosClientId: '565285676661-q7fquei91l1ciq7jk80h9k5pl0kam18j.apps.googleusercontent.com',
    iosBundleId: 'com.example.notemindApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt77tClWO581K8oItunWrlh7TMTYiBu5A',
    appId: '1:565285676661:web:f94e14b01dc6baca1ffa3c',
    messagingSenderId: '565285676661',
    projectId: 'notemind-app-7e7b4',
    authDomain: 'notemind-app-7e7b4.firebaseapp.com',
    storageBucket: 'notemind-app-7e7b4.firebasestorage.app',
    measurementId: 'G-F2Q7QTBDGC',
  );
}
